REM use '..' for dockerfile generated by VS
docker build -f dockerfile -t demo-hplusspotsweb:v1 ..


REM inside container port 80 by default. Map it on 5000
docker run -i -p 5000:80  demo-hplusspotsweb:v1
