#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["HPlusSportsWeb/HPlusSportsWeb.csproj", "HPlusSportsWeb/"]
RUN dotnet restore "HPlusSportsWeb/HPlusSportsWeb.csproj"
COPY . .
WORKDIR "/src/HPlusSportsWeb"
RUN dotnet build "HPlusSportsWeb.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HPlusSportsWeb.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Local
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HPlusSportsWeb.dll"]